#!/usr/bin/env bash
# load-completion.sh: Bash completion for load.sh
# Auto-generated by scripts/generate-completion.mjs — do not edit.
# Usage: source this file, or place it in /etc/bash_completion.d/

# Bash-only: skip silently when sourced from other shells (zsh, dash, ...)
[ -n "${BASH_VERSION:-}" ] || return 0 2>/dev/null || exit 0

_load_sh_completion() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"

  if [[ $COMP_CWORD -eq 1 ]]; then
    mapfile -t COMPREPLY < <(compgen -W "--completion --developer --dont-run --help --list --update -h ant aws-cli buildah byjg-gluo byjg-repo docker doctl eksctl gcloud gh helm java-corretto java-oracle java-temurin jq kubectl kustomize maven node-docker nvm php-docker podman qemu ssh-agent yq" -- "$cur")
    return
  fi

  case "${COMP_WORDS[1]}" in
    ant) mapfile -t COMPREPLY < <(compgen -W "--dry-run --help --manifest --version -h" -- "$cur") ;;
    aws-cli) mapfile -t COMPREPLY < <(compgen -W "--dry-run --help --manifest --version -h" -- "$cur") ;;
    buildah) mapfile -t COMPREPLY < <(compgen -W "--dry-run --help --manifest -h" -- "$cur") ;;
    byjg-gluo) mapfile -t COMPREPLY < <(compgen -W "--git-email --git-name --help --install-examples --manifest --mysql-uri --name --namespace --php-version --timezone --version -h" -- "$cur") ;;
    byjg-repo) mapfile -t COMPREPLY < <(compgen -W "--dry-run --help --install --list --manifest -h" -- "$cur") ;;
    docker) mapfile -t COMPREPLY < <(compgen -W "--channel --dry-run --help --manifest --no-group -h" -- "$cur") ;;
    doctl) mapfile -t COMPREPLY < <(compgen -W "--dry-run --force --help --manifest --version -h" -- "$cur") ;;
    eksctl) mapfile -t COMPREPLY < <(compgen -W "--dry-run --force --help --manifest --version -h" -- "$cur") ;;
    gcloud) mapfile -t COMPREPLY < <(compgen -W "--dry-run --help --manifest --version -h" -- "$cur") ;;
    gh) mapfile -t COMPREPLY < <(compgen -W "--dry-run --force --help --manifest --version -h" -- "$cur") ;;
    helm) mapfile -t COMPREPLY < <(compgen -W "--dry-run --force --help --manifest --version -h" -- "$cur") ;;
    java-corretto) mapfile -t COMPREPLY < <(compgen -W "--dry-run --force --help --manifest --version --yes -h -y" -- "$cur") ;;
    java-oracle) mapfile -t COMPREPLY < <(compgen -W "--dry-run --force --help --manifest --version --yes -h -y" -- "$cur") ;;
    java-temurin) mapfile -t COMPREPLY < <(compgen -W "--dry-run --force --help --manifest --version --yes -h -y" -- "$cur") ;;
    jq) mapfile -t COMPREPLY < <(compgen -W "--dry-run --force --help --manifest --version -h" -- "$cur") ;;
    kubectl) mapfile -t COMPREPLY < <(compgen -W "--dry-run --force --help --manifest --version -h" -- "$cur") ;;
    kustomize) mapfile -t COMPREPLY < <(compgen -W "--dry-run --force --help --manifest --version -h" -- "$cur") ;;
    maven) mapfile -t COMPREPLY < <(compgen -W "--dry-run --help --manifest --version -h" -- "$cur") ;;
    node-docker) mapfile -t COMPREPLY < <(compgen -W "--add --env --manifest --no-postinstall --postinstall --skip --volume" -- "$cur") ;;
    nvm) mapfile -t COMPREPLY < <(compgen -W "--dry-run --help --manifest -h" -- "$cur") ;;
    php-docker) mapfile -t COMPREPLY < <(compgen -W "--add --env --manifest --no-postinstall --postinstall --skip --volume" -- "$cur") ;;
    podman) mapfile -t COMPREPLY < <(compgen -W "--docker --dry-run --help --manifest -h" -- "$cur") ;;
    qemu) mapfile -t COMPREPLY < <(compgen -W "--arch --bridge --cpus --disk --dry-run --force --gpu --help --image --manifest --memory --name --no-cloud-init --port --purge-image --ssh-port -h" -- "$cur") ;;
    ssh-agent) mapfile -t COMPREPLY < <(compgen -W "--dry-run --help --key --manifest -h" -- "$cur") ;;
    yq) mapfile -t COMPREPLY < <(compgen -W "--dry-run --force --help --manifest --version -h" -- "$cur") ;;
    *) COMPREPLY=() ;;
  esac
}

complete -F _load_sh_completion load.sh
