#!/usr/bin/env bash
# load-completion.sh: Bash completion for load.sh
# Auto-generated by scripts/generate-completion.mjs — do not edit.
# Usage: source this file, or place it in /etc/bash_completion.d/

_load_sh_completion() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"

  if [[ $COMP_CWORD -eq 1 ]]; then
    mapfile -t COMPREPLY < <(compgen -W "--completion --developer --dont-run --help --list --update -h docker java-corretto java-oracle java-temurin maven node-docker nvm php-docker php-rest-api" -- "$cur")
    return
  fi

  case "${COMP_WORDS[1]}" in
    docker) mapfile -t COMPREPLY < <(compgen -W "--channel --dry-run --help --manifest --no-group -h" -- "$cur") ;;
    java-corretto) mapfile -t COMPREPLY < <(compgen -W "--dry-run --help --manifest --version -h" -- "$cur") ;;
    java-oracle) mapfile -t COMPREPLY < <(compgen -W "--dry-run --help --manifest --version -h" -- "$cur") ;;
    java-temurin) mapfile -t COMPREPLY < <(compgen -W "--dry-run --help --manifest --version -h" -- "$cur") ;;
    maven) mapfile -t COMPREPLY < <(compgen -W "--dry-run --help --manifest --version -h" -- "$cur") ;;
    node-docker) mapfile -t COMPREPLY < <(compgen -W "--manifest" -- "$cur") ;;
    nvm) mapfile -t COMPREPLY < <(compgen -W "--dry-run --help --manifest -h" -- "$cur") ;;
    php-docker) mapfile -t COMPREPLY < <(compgen -W "--add --manifest" -- "$cur") ;;
    php-rest-api) mapfile -t COMPREPLY < <(compgen -W "--git-email --git-name --help --install-examples --manifest --mysql-uri --name --namespace --php-version --timezone --version -h" -- "$cur") ;;
    *) COMPREPLY=() ;;
  esac
}

complete -F _load_sh_completion load.sh
