#!/usr/bin/env bash
# load-completion.sh: Bash completion for load.sh
# Auto-generated by scripts/generate-completion.mjs — do not edit.
# Usage: source this file, or place it in /etc/bash_completion.d/

_load_sh_completion() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"

  if [[ $COMP_CWORD -eq 1 ]]; then
    COMPREPLY=($(compgen -W "docker java-corretto java-oracle java-temurin maven node-docker nvm php-docker php-rest-api" -- "$cur"))
    return
  fi

  case "${COMP_WORDS[1]}" in
    docker) COMPREPLY=($(compgen -W "--channel --dry-run --help --manifest --no-group -h" -- "$cur")) ;;
    java-corretto) COMPREPLY=($(compgen -W "--dry-run --help --manifest --version -h" -- "$cur")) ;;
    java-oracle) COMPREPLY=($(compgen -W "--dry-run --help --manifest --version -h" -- "$cur")) ;;
    java-temurin) COMPREPLY=($(compgen -W "--dry-run --help --manifest --version -h" -- "$cur")) ;;
    maven) COMPREPLY=($(compgen -W "--dry-run --help --manifest --version -h" -- "$cur")) ;;
    node-docker) COMPREPLY=($(compgen -W "--manifest" -- "$cur")) ;;
    nvm) COMPREPLY=($(compgen -W "--dry-run --help --manifest -h" -- "$cur")) ;;
    php-docker) COMPREPLY=($(compgen -W "--add --manifest" -- "$cur")) ;;
    php-rest-api) COMPREPLY=($(compgen -W "--git-email --git-name --help --install-examples --manifest --mysql-uri --name --namespace --php-version --timezone --version -h" -- "$cur")) ;;
    *) COMPREPLY=() ;;
  esac
}

complete -F _load_sh_completion load.sh
