#!/usr/bin/env bash
# ssh-agent.sh: Configure ssh-agent startup and SSH key loading in your shell

set -euo pipefail

print_usage() {
  cat <<'USAGE'
load.sh ssh-agent -- [options]

Writes a shell init snippet that starts ssh-agent (if not already running)
and loads SSH keys on every new shell session.

By default, all private keys found in ~/.ssh are added. Use --key to add
only specific keys. Running this script again overwrites the previous config.

Options:
  -h, --help       Show this help and exit
  --dry-run        Print actions without executing them
  --manifest       Print installation manifest and exit
  --key <path>     Add this key (can be repeated for multiple keys)

Examples:
  load.sh ssh-agent
  load.sh ssh-agent -- --key ~/.ssh/id_ed25519
  load.sh ssh-agent -- --key ~/.ssh/id_rsa --key ~/.ssh/work_key
  load.sh ssh-agent -- --dry-run
USAGE
}

print_manifest() {
  cat <<'MANIFEST'
BIN_FILES=
FOLDERS=
SHELLRC_FILE=$HOME/.shellscript/shellrc/ssh-agent-init.sh
MANIFEST
}

# Parse flags
DRY_RUN=0
KEYS=()

while [[ ${1-} ]]; do
  case "$1" in
    -h|--help)   print_usage; exit 0 ;;
    --manifest)  print_manifest; exit 0 ;;
    --dry-run)   DRY_RUN=1 ;;
    --key)
      shift || { err "--key requires a value"; exit 2; }
      KEYS+=("$1")
      ;;
    *) err "Unknown option: $1"; print_usage; exit 2 ;;
  esac
  shift || true
done

require_cmd ssh-agent
require_cmd ssh-add

# If no keys specified, discover all private keys in ~/.ssh
if [[ ${#KEYS[@]} -eq 0 ]]; then
  while IFS= read -r -d '' f; do
    # Skip public keys, known_hosts, config, and authorized_keys
    [[ "$f" == *.pub ]]             && continue
    [[ "$f" == */known_hosts ]]     && continue
    [[ "$f" == */known_hosts.old ]] && continue
    [[ "$f" == */config ]]          && continue
    [[ "$f" == */authorized_keys ]] && continue
    KEYS+=("$f")
  done < <(find "${HOME}/.ssh" -maxdepth 1 -type f -print0 2>/dev/null)
fi

if [[ ${#KEYS[@]} -eq 0 ]]; then
  err "No SSH private keys found in ~/.ssh. Use --key <path> to specify one."
  exit 1
fi

log "Configuring ssh-agent with ${#KEYS[@]} key(s):"
for k in "${KEYS[@]}"; do
  log "  $k"
done

# Build the ssh-add lines for the init snippet
SSH_ADD_LINES=""
for k in "${KEYS[@]}"; do
  SSH_ADD_LINES="${SSH_ADD_LINES}  ssh-add \"${k}\" 2>/dev/null || true\n"
done

run "mkdir -p \"${SHELLSCRIPT_SHELLRC}\""

if [[ "$DRY_RUN" == "1" ]]; then
  log "[dry-run] Writing ${SHELLSCRIPT_SHELLRC}/ssh-agent-init.sh"
  log "[dry-run] Keys to be added:"
  for k in "${KEYS[@]}"; do
    log "[dry-run]   ssh-add \"${k}\""
  done
else
  # Build the init file — overwrite any previous version
  {
    printf '# ssh-agent-init.sh — generated by ssh-agent.sh (do not edit manually)\n'
    printf '# Start ssh-agent if not already running or socket is stale\n'
    printf 'if [ -z "${SSH_AUTH_SOCK-}" ] || ! ssh-add -l >/dev/null 2>&1; then\n'
    printf '  eval "$(ssh-agent -s)" >/dev/null\n'
    printf 'fi\n'
    printf '\n'
    printf '# Load SSH keys\n'
    for k in "${KEYS[@]}"; do
      printf 'ssh-add "%s" 2>/dev/null || true\n' "$k"
    done
  } > "${SHELLSCRIPT_SHELLRC}/ssh-agent-init.sh"

  log "Done. Shell init written to ${SHELLSCRIPT_SHELLRC}/ssh-agent-init.sh"
  log "It will be sourced automatically on every new shell session via load.sh."
fi